baseURL = "https://michael.stapelberg.ch/"
defaultContentLanguage = "en"
languageCode = "en-us"
summaryLength = 40
title = "Michael Stapelbergs Website"
theme = "stapelberg"
disableKinds = ["RSS"]
publishDir = "docs"
enableGitInfo = true

# Keep old behavior of hugo < 0.123:
capitalizeListTitles = false

# Raise generation timeout from 10s to 60s to account for our heavy image
# processing when rendering the site from scratch.
timeout = 60000

# TODO: this wipes .git of docs/ :O
# fix that in hugo/commands/hugo.go
# Delete files in docs/ if they vanish:
# cleanDestinationDir = true

# Enable triple backtick syntax for code blocks
pygmentsCodefences = true

pygmentsStyle = "friendly"

[pagination]
  pagerSize = 30

# TODO: switch to pygmentsUseClasses for CSS-based syntax highlighting?
# https://hugodown.r-lib.org/articles/config.html
# https://harrycresswell.com/articles/performant-syntax-highlighting-in-hugo/

# TODO: this makes menus per-language,
# which is undesired (most content is not translated).

# [languages]
#   [languages.en]
#     title = "English"
#     weight = 1
# 
#   [languages.de]
#     title = "Deutsch"
#     weight = 2

[taxonomies]
tag = "tags"

[permalinks]
tags = "/posts/tags/:slug/"

[blackfriday]
  # Disable turning regular quotes into smart quotes (harmful for code blocks):
  smartypants = false

[params]
  description = "Michael Stapelberg’s private website, containing articles about computers and programming, mostly focused on Linux."

[mediaTypes."application/atom"]
suffixes = ["xml"]

[outputFormats.Atom]
mediaType = "application/atom"
baseName = "feed"
isPlainText = false

[outputs]
home = [ "HTML", "Atom" ]
term = [ "HTML", "Atom" ]

# Prevent <!-- raw HTML omitted -->:
[markup.goldmark.renderer]
unsafe = true

[module]
[[module.mounts]]
  source = 'static'
  target = 'static'
  # Not using [!s][!v][!g][!o] because that doesn’t match bitpacking256v32.svg
  excludeFiles = "turbopfor/*[!g][!o].svg"
# TODO(https://github.com/gohugoio/hugo/issues/9076): add "turbopfor/Makefile"

[privacy]
  [privacy.x]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
