---
permalink: /post/7
layout: post
date: 2010-04-01 16:41:41 +02:00
title: "
Wenn vmware-modconfig sich mi…"
---
<p>
Wenn <code>vmware-modconfig</code> sich mit der Meldung „gcc and kernel headers
must be installed” beschwert, obwohl beides installiert ist, könnte das daran
liegen, dass unter Linux 2.6.33 die Dateien <code>utsrelease.h</code> und
<code>autoconf.h</code> nicht mehr in <code>include/linux/</code>, sondern in
<code>autogenerated/</code> landen. Folgender Workaround schafft abhilfe, bis
VMware eine funktionierende Variante ausliefert:
</p>

<pre>
cd /lib/modules/$(uname -r)/build/include/linux
ln -s ../generated/utsrelease.h .
ln -s ../generated/autoconf.h .
</pre>

